package com.jobc.j112kilo.utils


const val PATH_IMAGE = "/images/"
const val PATH_IMAGES_AVATAR = "/images/avatar/"
const val IMG_AVATAR = "avatar.jpg"
const val PATH_IMAGES_DRIVER_LICENSE = "/images/license/"
const val IMG_DRIVING_LICENSE_FIRST = "drivingLicenseFirst.jpg"
const val IMG_DRIVING_LICENSE_SECOND = "drivingLicenseSecond.jpg"
const val PATH_IMAGES_CARS = "/images/cars/"
const val IMG_CAR = "photoCar.jpg"
const val IMG_TECHNICAL_PASSPORT_FIRS = "technicalPassportPhotoFirst.jpg"
const val IMG_TECHNICAL_PASSPORT_SECOND = "technicalPassportPhotoSecond.jpg"
const val ERROR_DATA = "error"
const val TAKE_PICTURE = "take_photo"
const val SEARCH_PHOTO_IN_GALLERY = "search_photo_in_gallery"
const val LAYOUT_FOR_AVATAR = "layout_avatar"
const val  LAYOUT_FOR_DRIVER_LICENSE = "layout_driver_license"
const val USER_TOKEN_DATABASE = "userTokenDatabase.db"
const val USER_DATABASE = "userDatabase.db"
const val CITY_FOUND_DATABASE = "cityFoundDatabase.db"
const val CARS_DATABASE = "cityCars.db"
const val VIEWING_AGREEMENT = "https://*******/ru/site/site-agreement"
const val VIEWING_POLiCY = "https://*******/ru/site/privacy-policy"